%macro ExclDiag(lib,base,excl,new=,prefix=D);
    %local N nsets diag len;
    %if "&new"="" %then %let new = &base;
    %if %symexist(LPR&excl) %then %do;
        data &lib..&base.ALL;
            set &lib..&base.ALL;
	    outcome = "&new";
            %let nsets=%sysfunc(countw(&&LPR&excl));
            %do N=1 %to &nsets;
                %let diag=%lowcase(%scan(&&LPR&excl,&N));
                %let len=%length(&prefix.&diag);
                if lowcase(substr(diagnose,1,&len))=lowcase("&prefix.&diag") then delete;
                %end;
            %runquit;
            %end;
        %else %put WARNING: Exclusion code group &excl is not defined;
        %mend;
